In [1]:
import numpy as np

In [4]:
l=[1,2,3,4]
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4,5]

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
c = a

In [15]:
c

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [18]:
c[0] = 100 #solocopy

In [19]:
c

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
d = np.copy(a) #deepcopy

In [22]:
d

array([100,   2,   3,   4])

In [23]:
a[1]=400 

In [25]:
d  

array([100,   2,   3,   4])

In [26]:
np.fromfunction(lambda i,j: i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
for i in range(5):
    print(i*i)

0
1
4
9
16


In [30]:
iterable = (i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [34]:
np.fromstring("234 234", sep = ' ')

array([234., 234.])

In [35]:
np.fromstring("4,5", sep = ' ,')

array([4., 5.])

In [36]:
# numpy data type

In [37]:
l =[1,2,3,4,5]

In [38]:
ar = np.array(l)
ar

array([1, 2, 3, 4, 5])

In [39]:
ar.ndim

1

In [40]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [41]:
ar2.ndim

2

In [42]:
ar.size

5

In [43]:
ar2.size

8

In [45]:
ar.shape

(5,)

In [46]:
ar2.shape

(2, 4)

In [47]:
ar.dtype

dtype('int32')

In [48]:
ar2.dtype

dtype('int32')

In [49]:
range(5)

range(0, 5)

In [50]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
np.arange(2.3,4.5)

array([2.3, 3.3, 4.3])

In [53]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [55]:
np.linspace(start=1,stop=5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [59]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [60]:
np.ones(1)

array([1.])

In [62]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [65]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.eye(4) # identity matrix (square matrix)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [68]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [70]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [72]:
arr = np.random.randn(3,4)# based on standard normal dtribution then mean = 0,std =1

In [73]:
arr

array([[-1.01715803,  0.79436633, -0.18725872,  1.60758637],
       [-1.12214283, -0.18283743, -0.57633205, -0.20727248],
       [-0.93763645,  0.00756755,  0.79892308, -0.47999499]])

In [74]:
import pandas as pd

In [75]:
pd.DataFrame(arr)

0         1         2         3
0 -1.017158  0.794366 -0.187259  1.607586
1 -1.122143 -0.182837 -0.576332 -0.207272
2 -0.937636  0.007568  0.798923 -0.479995

In [77]:
np.random.rand(3,4)

array([[0.83753436, 0.16884759, 0.28925646, 0.37608559],
       [0.96337682, 0.92632705, 0.13440593, 0.63028087],
       [0.86199422, 0.91771126, 0.2526903 , 0.80919086]])

In [79]:
pd.DataFrame(np.random.randint(1,100,(3,4)))

0   1   2   3
0   3  61  94  69
1  45  18  38  52
2  77  51  19  56

In [80]:
arr = np.random.randn(3,4)

In [81]:
arr

array([[-0.61218128,  1.73473518,  0.42967555,  0.89434089],
       [ 0.56230715,  1.32315943, -2.35671068, -0.5273535 ],
       [ 1.09372892, -2.03442202,  0.07384313,  0.26875596]])

In [83]:
arr.reshape(6,-1)

array([[-0.61218128,  1.73473518],
       [ 0.42967555,  0.89434089],
       [ 0.56230715,  1.32315943],
       [-2.35671068, -0.5273535 ],
       [ 1.09372892, -2.03442202],
       [ 0.07384313,  0.26875596]])

In [84]:
arr[1]

array([ 0.56230715,  1.32315943, -2.35671068, -0.5273535 ])

In [85]:
arr[1][1]

1.3231594252410859

In [86]:
arr1 = arr.reshape(6,-1)
arr1

array([[-0.61218128,  1.73473518],
       [ 0.42967555,  0.89434089],
       [ 0.56230715,  1.32315943],
       [-2.35671068, -0.5273535 ],
       [ 1.09372892, -2.03442202],
       [ 0.07384313,  0.26875596]])

In [87]:
arr1[1][1]

0.8943408901936593

In [88]:
arr1[2:5,1]

array([ 1.32315943, -0.5273535 , -2.03442202])

In [89]:
arr = np.random.randint(1,100,(5,5))

In [90]:
arr

array([[98, 81,  4, 82, 65],
       [98, 73, 90, 30, 88],
       [36, 53,  2, 98, 69],
       [26, 47, 87, 32, 41],
       [71, 11, 60, 87, 66]])

In [91]:
arr>50

array([[ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True],
       [False, False,  True, False, False],
       [ True, False,  True,  True,  True]])

In [92]:
arr[arr>50]

array([98, 81, 82, 65, 98, 73, 90, 88, 53, 98, 69, 87, 71, 60, 87, 66])

In [93]:
arr

array([[98, 81,  4, 82, 65],
       [98, 73, 90, 30, 88],
       [36, 53,  2, 98, 69],
       [26, 47, 87, 32, 41],
       [71, 11, 60, 87, 66]])

In [94]:
arr[2:4,[1,2]]

array([[53,  2],
       [47, 87]])

In [95]:
arr[0][0] = 400

In [96]:
arr

array([[400,  81,   4,  82,  65],
       [ 98,  73,  90,  30,  88],
       [ 36,  53,   2,  98,  69],
       [ 26,  47,  87,  32,  41],
       [ 71,  11,  60,  87,  66]])

In [97]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [98]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [1, 2, 2]])

In [99]:
arr2

array([[2, 2, 1],
       [1, 1, 2],
       [1, 1, 1]])

In [100]:
arr1+arr2

array([[3, 4, 2],
       [2, 2, 4],
       [2, 3, 3]])

In [101]:
arr1*arr2

array([[2, 4, 1],
       [1, 1, 4],
       [1, 2, 2]])

In [104]:
arr1@arr2 # matrix multipication using @ simbol

array([[5, 5, 6],
       [5, 5, 5],
       [6, 6, 7]])

In [105]:
arr1/0

C:\Users\DELL\AppData\Local\Temp\ipykernel_9176\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [106]:
arr1+100

array([[101, 102, 101],
       [101, 101, 102],
       [101, 102, 102]])

In [108]:
arr1**2

array([[1, 4, 1],
       [1, 1, 4],
       [1, 4, 4]], dtype=int32)

In [110]:
#Numpy – Broadcasting.

arr = np.zeros((4,4))

In [111]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
row = np.array([1,2,3,4])

In [113]:
row

array([1, 2, 3, 4])

In [114]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [116]:
row.shape

(4,)

In [119]:
col = np.array([[1,2,3,4]])

In [120]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [121]:
col

array([[1, 2, 3, 4]])

In [122]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [123]:
array = np.random.randint(1,4,(3,4))

In [124]:
array

array([[1, 2, 3, 1],
       [1, 3, 3, 1],
       [2, 2, 1, 2]])

In [126]:
np.sqrt(array)

array([[1.        , 1.41421356, 1.73205081, 1.        ],
       [1.        , 1.73205081, 1.73205081, 1.        ],
       [1.41421356, 1.41421356, 1.        , 1.41421356]])

In [127]:
np.log10(array)

array([[0.        , 0.30103   , 0.47712125, 0.        ],
       [0.        , 0.47712125, 0.47712125, 0.        ],
       [0.30103   , 0.30103   , 0.        , 0.30103   ]])

In [128]:
np.expm1(array)

array([[ 1.71828183,  6.3890561 , 19.08553692,  1.71828183],
       [ 1.71828183, 19.08553692, 19.08553692,  1.71828183],
       [ 6.3890561 ,  6.3890561 ,  1.71828183,  6.3890561 ]])

In [129]:
arr = np.random.randint(1,4,(3,4))

In [130]:
arr

array([[2, 2, 2, 3],
       [1, 3, 2, 3],
       [3, 2, 3, 3]])

In [131]:
arr.shape

(3, 4)

In [132]:
arr.reshape(2,6)

array([[2, 2, 2, 3, 1, 3],
       [2, 3, 3, 2, 3, 3]])

In [134]:
arr.reshape(6,2)

array([[2, 2],
       [2, 3],
       [1, 3],
       [2, 3],
       [3, 2],
       [3, 3]])

In [135]:
arr.T

array([[2, 1, 3],
       [2, 3, 2],
       [2, 2, 3],
       [3, 3, 3]])

In [137]:
arr.flatten() # two dim arr convert one dim array

array([2, 2, 2, 3, 1, 3, 2, 3, 3, 2, 3, 3])

In [138]:
arr1 = np.array([1,2,3,4,5])

In [139]:
arr1

array([1, 2, 3, 4, 5])

In [140]:
arr1.ndim

1

In [141]:
np.expand_dims(arr1,axis = 1) # change dim 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [142]:
arr

array([[2, 2, 2, 3],
       [1, 3, 2, 3],
       [3, 2, 3, 3]])

In [143]:
np.squeeze(arr)

array([[2, 2, 2, 3],
       [1, 3, 2, 3],
       [3, 2, 3, 3]])

In [144]:
data = np.array([[1],[2],[3]])

In [145]:
data

array([[1],
       [2],
       [3]])

In [146]:
np.squeeze(data) # convert array single row

array([1, 2, 3])

In [147]:
np.repeat(arr,3)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 1, 1, 1, 3, 3, 3, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 3])

In [148]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [149]:
arr1

array([1, 2, 3, 4, 5])

In [150]:
np.diag(arr1) # convert diagnol

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [151]:
#Numpy - Binary Operators.

In [164]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [153]:
arr1

array([[2, 5, 7, 7],
       [7, 2, 4, 8],
       [5, 5, 3, 2]])

In [165]:
arr2

array([[9, 8, 7, 7],
       [9, 7, 2, 1],
       [9, 3, 6, 2]])

In [166]:
arr1+arr2

array([[10, 10, 16, 10],
       [12,  9,  7, 10],
       [13,  8, 10,  4]])

In [167]:
arr1-arr2

array([[-8, -6,  2, -4],
       [-6, -5,  3,  8],
       [-5,  2, -2,  0]])

In [168]:
arr1*arr2

array([[ 9, 16, 63, 21],
       [27, 14, 10,  9],
       [36, 15, 24,  4]])

In [169]:
arr1/arr2

array([[0.11111111, 0.25      , 1.28571429, 0.42857143],
       [0.33333333, 0.28571429, 2.5       , 9.        ],
       [0.44444444, 1.66666667, 0.66666667, 1.        ]])

In [170]:
arr1%arr2

array([[1, 2, 2, 3],
       [3, 2, 1, 0],
       [4, 2, 4, 0]], dtype=int32)

In [171]:
arr1**arr2

array([[      1,     256, 4782969,    2187],
       [  19683,     128,      25,       9],
       [ 262144,     125,    4096,       4]], dtype=int32)

In [172]:
arr1

array([[1, 2, 9, 3],
       [3, 2, 5, 9],
       [4, 5, 4, 2]])

In [173]:
arr2

array([[9, 8, 7, 7],
       [9, 7, 2, 1],
       [9, 3, 6, 2]])

In [174]:
~arr1

array([[ -2,  -3, -10,  -4],
       [ -4,  -3,  -6, -10],
       [ -5,  -6,  -5,  -3]], dtype=int32)

In [175]:
arr1|arr2

array([[ 9, 10, 15,  7],
       [11,  7,  7,  9],
       [13,  7,  6,  2]], dtype=int32)

In [176]:
arr1>arr2

array([[False, False,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [177]:
#Numpy - String Functions.

In [179]:
arr = np.array(['sudh' , "Kumar"])

In [180]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [181]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [182]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [183]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [185]:
#Numpy - Mathematical Functions.

In [186]:
arr1

array([[1, 2, 9, 3],
       [3, 2, 5, 9],
       [4, 5, 4, 2]])

In [187]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743,  0.41211849,  0.14112001],
       [ 0.14112001,  0.90929743, -0.95892427,  0.41211849],
       [-0.7568025 , -0.95892427, -0.7568025 ,  0.90929743]])

In [188]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.91113026, -0.9899925 ],
       [-0.9899925 , -0.41614684,  0.28366219, -0.91113026],
       [-0.65364362,  0.28366219, -0.65364362, -0.41614684]])

In [189]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986, -0.45231566, -0.14254654],
       [-0.14254654, -2.18503986, -3.38051501, -0.45231566],
       [ 1.15782128, -3.38051501,  1.15782128, -2.18503986]])

In [190]:
np.tanh(arr1)

array([[0.76159416, 0.96402758, 0.99999997, 0.99505475],
       [0.99505475, 0.96402758, 0.9999092 , 0.99999997],
       [0.9993293 , 0.9999092 , 0.9993293 , 0.96402758]])

In [191]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.95424251, 0.47712125],
       [0.47712125, 0.30103   , 0.69897   , 0.95424251],
       [0.60205999, 0.69897   , 0.60205999, 0.30103   ]])

In [193]:
np.power(arr1,3)

array([[  1,   8, 729,  27],
       [ 27,   8, 125, 729],
       [ 64, 125,  64,   8]], dtype=int32)

In [194]:
np.mean(arr1)

4.083333333333333

In [195]:
np.median(arr1)

3.5

In [196]:
np.std(arr1)

2.4986107250941583

In [197]:
np.var(arr1)

6.2430555555555545

In [198]:
#sort,search & counting function

In [200]:
l = [2,4,2,3,4,5,4,6,78,3,68,9,9,7,90,0,7,6,8]

In [201]:
arr =np.array(l)

In [202]:
arr

array([ 2,  4,  2,  3,  4,  5,  4,  6, 78,  3, 68,  9,  9,  7, 90,  0,  7,
        6,  8])

In [203]:
np.sort(arr)

array([ 0,  2,  2,  3,  3,  4,  4,  4,  5,  6,  6,  7,  7,  8,  9,  9, 68,
       78, 90])

In [204]:
np.searchsorted(arr,78)

14

In [207]:
arr1 = np.array([0,0,344,565,3,344,0,0,86,0])

In [208]:
np.count_nonzero(arr1)

5

In [209]:
arr

array([ 2,  4,  2,  3,  4,  5,  4,  6, 78,  3, 68,  9,  9,  7, 90,  0,  7,
        6,  8])

In [210]:
np.where(arr > 6)

(array([ 8, 10, 11, 12, 13, 14, 16, 18], dtype=int64),)

In [211]:
np.extract(arr >3,arr)

array([ 4,  4,  5,  4,  6, 78, 68,  9,  9,  7, 90,  7,  6,  8])

In [212]:
np.extract(arr >5,arr)

array([ 6, 78, 68,  9,  9,  7, 90,  7,  6,  8])

In [213]:
#Numpy - Byte Swapping.

arr.byteswap()

array([  33554432,   67108864,   33554432,   50331648,   67108864,
         83886080,   67108864,  100663296, 1308622848,   50331648,
       1140850688,  150994944,  150994944,  117440512, 1509949440,
                0,  117440512,  100663296,  134217728])

In [214]:
#Numpy - Copies &Views.

In [215]:
arr

array([ 2,  4,  2,  3,  4,  5,  4,  6, 78,  3, 68,  9,  9,  7, 90,  0,  7,
        6,  8])

In [216]:
a = np.copy(arr)

In [217]:
b = arr.view()

In [218]:
b

array([ 2,  4,  2,  3,  4,  5,  4,  6, 78,  3, 68,  9,  9,  7, 90,  0,  7,
        6,  8])

In [219]:
arr

array([ 2,  4,  2,  3,  4,  5,  4,  6, 78,  3, 68,  9,  9,  7, 90,  0,  7,
        6,  8])

In [220]:
b[0]=667

In [221]:
b

array([667,   4,   2,   3,   4,   5,   4,   6,  78,   3,  68,   9,   9,
         7,  90,   0,   7,   6,   8])

In [222]:
arr

array([667,   4,   2,   3,   4,   5,   4,   6,  78,   3,  68,   9,   9,
         7,  90,   0,   7,   6,   8])

In [223]:
#Numpy - Matrix Library.

In [224]:
import numpy.matlib as nm

In [225]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [226]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [227]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [228]:
#Numpy - Linear Algebra

In [229]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [230]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [232]:
np.dot(arr1,arr2)

array([[ 4,  6],
       [10, 12]])